apiVersion: v1
kind: Namespace
metadata:
  name: webapp

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp
  namespace: webapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
        - name: webapp-container
          image: rahala7/auto-ci-cd
          ports:
            - name: http
              containerPort: 3000
