apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: helloapp
  namespace: webapp
  name: helloapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: helloapp
  template:
    metadata:
      labels:
        app: helloapp
    spec:
      containers:
      - image: rahala7/auto-ci-cd
        name: helloapp
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        resources: {}
