apiVersion: v1
kind: Service
metadata:
  labels:
    app: service
  name: service
  namespace: jenkins
spec:
  ports:
  - name: helloapp
    port: 80
    protocol: TCP
    targetPort: 80
    nodePort: 3030
  selector:
    app: helloapp
  type: LoadBalancer
status:
  loadBalancer: {}
