apiVersion: v1
kind: Service
metadata:
  labels:
    app: webapp
  name: webapp
  namespace: webapp
spec:
  ports:
  - name: webapp-port
    port: 80
    protocol: TCP
    targetPort: 80
    nodePort: 3000
  selector:
    app: webapp
  type: LoadBalancer
status:
  loadBalancer: {}
